spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sports_event_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.sportsplatform: DEBUG
